find any usbmodem that isn't Caterina

diff --git a/bin/flash b/bin/flash
--- a/bin/flash
+++ b/bin/flash
@@ -6,5 +6,5 @@ make maybe_build
 stty -f /dev/cu.usbmodemCatreusE1 1200
 sleep 3
 
-export DEVICE_PORT_BOOTLOADER=$(ls /dev/cu.usbmodem141*)
-make flash
+export DEVICE_PORT_BOOTLOADER=$(ls /dev/cu.usbmodem* | grep -v usbmodemC)
+[[ -n "$DEVICE_PORT_BOOTLOADER" ]] && make flash || echo "Couldn't find a device for flashing!"
